### ISSUE TITLE
Safari/Firefox: TypeError: null is not an object

### ISSUE THREAD

**Issue by Sanderand** [webcomponents/hello-world-element#7]
I was checking out the functionality on a freshly cloned github project. Chrome works absolutely fine for me, but Safari and Firefox won't display anything and give me the following errors:

In Safari:
TypeError: null is not an object (evaluating 'thisDoc.querySelector('template').content')

In Firefox:
TypeError: thisDoc.querySelector(...) is null

My system:
Safari: Version 8.0 (10600.1.25.1)
Firefox: 31.0
OS: OS X Yosemite 10.10.1 (14B25)

Does anyone have the same problem or a solution for that?

**Comment by zenorocha** [comment]
Fixed in #8
